export const analyticsEvents = {
  landingPageViewed: "landing_page_viewed",
  landingPrimaryCtaClicked: "landing_primary_cta_clicked",
  landingLoginClicked: "landing_login_clicked",
  landingSectionCtaClicked: "landing_section_cta_clicked",
  landingPricingViewed: "landing_pricing_viewed",
  landingLearningArtifactsViewed: "landing_learning_artifacts_viewed",
  landingFaqOpened: "landing_faq_opened",
  landingFooterCtaClicked: "landing_footer_cta_clicked",
  loginPageViewed: "login_page_viewed",
  emailSignupStarted: "email_signup_started",
  emailSignupCompleted: "email_signup_completed",
  emailLoginStarted: "email_login_started",
  emailLoginCompleted: "email_login_completed",
  googleLoginClicked: "google_login_clicked",
  googleLoginCompleted: "google_login_completed",
  authErrorShown: "auth_error_shown",
  signupStarted: "signup_started",
  signupCompleted: "signup_completed",
  loginCompleted: "login_completed",
  logoutClicked: "logout_clicked",
  dashboardViewed: "dashboard_viewed",
  studentProfileSetupStarted: "student_profile_setup_started",
  studentProfileCreated: "student_profile_created",
  classScheduleStarted: "class_schedule_started",
  classScheduleDetailsSubmitted: "class_schedule_details_submitted",
  paymentInitiated: "payment_initiated",
  paymentCompleted: "payment_completed",
  paymentFailed: "payment_failed",
  classDetailViewed: "class_detail_viewed",
  tuitionDetailViewed: "tuition_detail_viewed",
  adminDashboardViewed: "admin_dashboard_viewed",
} as const;

export type AnalyticsEventName =
  (typeof analyticsEvents)[keyof typeof analyticsEvents];
